# Generated by Django 4.2.29 on 2026-03-29 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('last_username', models.CharField(blank=True, max_length=150)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
